apiVersion: v1
kind: Secret
metadata:
    name: paperless-oicd-settings
stringData:
    PAPERLESS_APPS: ENC[AES256_GCM,data:/iZmPPKHtNWtLHm5dE+knynL/JglKA+t2l9KSParbd0FIAxe5mMCypj17KBbqA==,iv:fTwgKRwIxe8xwEXIvpXBIuN/xj+tXxqNfJNLEGRUr18=,tag:7CBB/6YswDjNWzQFp7wOmA==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:WsyJnSwO6EDADTn2jpaNoCknpTmtble3dUkbjySGgfdPH9lEQghCLwv268rjWbmU13/EPMONx5SGoFJ/djgyrKk+89u36qk4CQpCs9/98JX07xsGV6+FSwCpxoDSdUosME871XzUNJP2+Chj8gN9dYUcxOZT3ZsdSKhRHBBd6Ww3P/dLOgh2n68MZ2F5u+A6pDpRwtf0YQS3jKy+1uJWMgMtl+5rQTBesqyAaB6WGELjmS7r7DgT0EIdX4A8+/n8mf/JtOLtgkEE9ysu/zc9JEzBaz0QI+XfwMl68V3dvF6UFTgj7nIqm/FLbFjyMQ4jTQwihu7yYsxUxIrp2eIqDDDGAJdldWneRBI8adh3VBtgWuOWG/Vh2oOex3ajTOqWLR73KupCNelFAN8Tztf9xbuy6FUROZWpf8TqAmXTlUR2EGjeKq4ZnQBu33eMVRgGn5KlvvXCxoH8N+168UlRxQCX4ZLnYiSed+stBWHnw2Q4cfHD1P6ZJkUC23RO3xthzd6HdxevRtSFxKXT5twILMXmV9nTKk/72lFkZiOS+fqt7J9EJSBe0lKDBg3dCJYhrFI53HimhohgCQyF4gspLhOrCicAsjO6l/Oaa7svytDs0AneZn0HE1j6Y5vGGNcsjhzGoBB/hAt6XI4L34X3SVwVdq88zpmQj0DHyqHBImoJfB2/SWqHCmB+Rmp5AV1dQNRdZnO7l6OHQ2or+ldYLclzLSnkrKh+Bq8AYvpo+/UARGfN1pAhXLLPfCiy7UkNySo2mwtldL5a8B2n46Wf7J9a8k0WSyaHXUKdTGxxUOVdlkR+qxvdZEu3p/wYyA==,iv:wNYF0umxRdQjan9gf7HeewvkNKhaUnVf76Jbm8jB57I=,tag:8UiuZNnIiXNganY14HLSYQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBeWwraU44
            eVBpenBPT3V6bEdQd1hIand2OEFMcm5URmU2Wkc4bEc1SWxkcwp0TkU5N2F5UU82
            QUo0cXVSY2UvUFQvV1BXK0xTQ0JlWGZHcmdvSlBKZy9NCi0tLSBUUTZKUVFhQ3Fh
            TzlNRGFwaVdpN1R2SnZubnk2NTFRR0pKZ09TOENQczdvCsjT72mUiM/LRrDzKUdX
            VVbThCIwGCIss28lrtvS2Zj+n/L/aGlofVzhRxh5CTK4gY3STUYxQVjfs3fLNqfE
            QDo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBMzFJTkhQ
            NG9BdzMwZGpoYVN4THNGWTEwbFF4L0F6MlpwQXZjYTlvNmF2SQp5V0paaUl5MXFE
            ZEY0c3hNeFdLTFVkdmdPQVV0Z01xWGllSyt4SnowUnNZCi0tLSBMbTA0bE9BRk40
            aVpFSVBRMFQybU03WlU1dGszckJmQmpWS2RXdUV0WHQ0CpRDBV/4A0M/HF6dV/0c
            i6DZKgNeAF015ZTHivUsqwy6hR45BoYiJbg2YcwpM4jzx8sl80HODkLcWP1MVrCg
            zWc=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbmI0V0xKb2N0aVQ4VkR6
            MmcvalhhZy8vcnV5cm5UcERuelFWeVhOVVIwCnZKVjQxOEhPeUdjN2xxRy82djlW
            bDQwcnNqT1ZZeXBzVjhBbzh0eWdUVFUKLS0tIHlSclBXQW4xWml1aERCOXdRVkhE
            VkZFQzNWU3NSRzNCTVpmVEd1emxuSUEKTOHbdlgEQZvqPSjdMxFlCSETf/Tk5RVn
            YIcWgrvMbktddAHfLS4fs9RwwQq8NPNwn/1pZvi0EltSsDuNdIxWZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T16:29:50Z"
    mac: ENC[AES256_GCM,data:gGoopLZvTDnv2fXtI9b4F43ELvzZTnCADNUP6Dq4cLr/QD5CsnwtvswaRoYVaVunyJkfBpTsL3SEKiKZC62HuaNN5Ss1wuviBIKVbj3/vIQqUKvJj3sChh/GD5Y4mNlAYf/LvJ7FsI5Cp3kH77bZI2YhFIWsKP9POhO0PBn2mqc=,iv:fC6h6JYcKlDp1tBjrd42bC+iGrsBr9xBwLihNBpSUcI=,tag:vq6IUuPtRnbFQEv31yj22Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
