apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helm-release.yaml
  - resources/oci-repo.yaml
  - resources/postgres.yaml
  - resources/postgres-db-secret.yaml
  - resources/cluster-backup-creds.yaml
  - resources/certificate.yaml

