apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: matrix-turn-tls
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`turn.matrix-test.jackhil.de`)
    priority: 10
    services:
    - name: matrix-matrix-rtc-sfu-turn-tls
      port: 31443
  tls:
    passthrough: true
