apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:7JQzo8FF/Ff6fVNV4icTRB5hZhPDRNQoDPwISIYne3Nt/vgT78q+L9RIjDJcRspOrAeWu41SWygqxvOu0APT0wn1wfFmiKe85yHR4vfbnKNvhWWI4P6ATvDK/YHVDd5jIDUkcZNxNqoljq4cZ6Xbo1uLlvLg+ZS/x0Z9M2D6E6DiqsRvuT36Ml5pOoBHhjIne1fIgydyr9ClXi5x0mT++Y5xzS1YJ/P9CJqnK2AKLLOzKE9vOj7EnsSAd/cfLTWWqQ5zI1YSYfqEseuny3Av1gAMnUTjcWXROl4AbV2N64aFBVomOdun65wRxzCjndFHaQHnZbyfI0NNVYyxluds/YpfCD5qPtMpm1G6AdrzPHVBIKJ6pFTCqAW8vchUGRGxRyIamWhsxHYBTwD8za4K15TrMpZ7EphnzBxD84sy98ZADnONUSJ1W1k4H7n7lvGmLa4SkTLBYmUxr7QhUmtwRuQyvfYt9rYVPcTgN8clWfw3oWoq3r75m2z099dh9xvXB3Rv8NindvNGzY8kT/o47FLDgWcaS9f3yO66Wv8RDTF4QxMnM1pPMFJzmROrJvPWprNz6uztIimOWE2+LCelO48aEsWQNY/0+zdnNVmwVBBABN/lFlSnYB7CA8GPMhDYngA3gu5QPRXU/BmJ2qlrDpWGkbUoGptWiHM/ombhUOUy4ZREC4ByHcoF1+meW9SiM7GdUYGSWOJ7k0bz0Rob3OerzwMbXpVE0V8bFGGquNKTUsmdhJHaaIPNz1o+WxSLowYkOtrEgkxzHuEGDMnkYSrtSNIDTw/8c3sFSHYrC1TzUg0fdgc0AsVBfwDHB6GaOuEjpiZE+/WPCLB9P0hvrOR4PxSEjt+y5QGfHcprBvwLfo1xNMrM9BPXtG3tEEUjkSLA6+WlqbOH731QjkcfHh5E4XhEwCiA/uHUh5nI/PZLjxdQ8PLhF9q6bUq/5FQcfcnXcDS2tuIHwyyOFqDUZ+89H5nOL/AARA2CcuGenhqGk/8Y3gMZt/+RS8Adoxd6NyhIr1QHyBGhAK5Dx0WOWdPE2/9urBlaoHMMwgGvPWC9DNdVjrtydsTI5uvdkicYsqFR60+WeQPzsTc2tczZPhaL0Zd873yoMf7+AIhDIYJdRY0N5z1CxgpIA3voj/CbKQdporFnWoQFG+PTOBzuo7LRWN7KDTXFBTEAA+KhBBPLOzik7/QmMLC3zDe9YRECRXcPp9xB0SWLe/3Sdcjed+V+qWuhs5kk3zjl6xbTvOIIkBkkiQPZGZqieUaAtyCdT6uZI8zlCDUaDiA3KoeKyy9y0EhZTH9pNGbCoOSVwsQ9rdDtI/67T84QNDOypRWPLvFQYNeznl5OrjrAJVniMc1KIzTM4ZrAiRp8ZUX7ejgJjkd04kZVxBhr2oA3ftA/hvOwIAr4Wu+N2ai4AsyTUTMvcLkRHXqKIhkCFMYhTNiTfXpeiwcJ6OtYV8c8oz0XijyYyyaCPDsb9SyNQfgk2hhixbYFNhe5WPhKKIhkpsqB4h/aW9+LokVRQ0E7zsKsPQKVdj9RJpWlP0l6RSuIrCmdIhpeMdZVeRtEtjjJpK5r/+AUPiWcyYoo7S1qAN5ij8wy27zu3hmpEm/y0WK9VkHbH/dCamvYCy4UYN7cbMMH0ei5GiweNgAnDChHQlBGhyK6SEcM7E9g7Bui6Ccp8FcUG3I+0Flcx4pgFXAknd25+AuPuJoUKVOz/aV7P91uM2gs0AhivaSWbCyhVXSXKAMWbX8vcH9xaKQhX6AkWgRaOvQAKjMGbbzgdvAQgERTovhKJWdge+lSH01WY1zFsDWAqX3DdMtlydjGpTYfQkuoL+b2fJUJjeI+aDKr3RyHy7BWEUPbYTkQMtAWDlNwc4mpFWUT/OehdJinnW3ZfjMinb7mVVTQJmw+7iAn23z6aOVjQ3SRnMr3KRdSp7NRlg0BscjjEj0LMouNXjj9BaBORnq3sKy5TKR2izx86/B9NnyxhYN6ONY/BmKmgVPOlHvF3RgRaT2w7PrFM8mmBP1XrUFJcLefJ4lukbVYbx1kbsipD4XVNDHW0mEEGOPMpV5zKl9TUW7U+qNgPDLLYCIBnM1vTWOl9KOGNYcF6zV2mF2obuLG3ANXuMuJOTjYEA9MnzBniOh5c5uJDmHwU1W07adUAVZUsjbsKHZgQFQByogFCcQE3Psaa9lWpD28RKQIqjonbcnp7WRtEyoNaFwwCGbSW2EOdLQDwN/Bl7gYWom7JMfSdkhxxOE7LZlciDTcEmWzdm0c7RtK7aDqqYYzhe4Ivn/z9vfeXf/SFt0VwA==,iv:yheoA5stamVwYFB7pt+e+xpCAKwZpj0dl5su0c8sSUA=,tag:g2wUaY3fSvJWEfHUSqMl9A==,type:str]
sops:
    age:
        - recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBc1Y0NjRk
            ZGdGTDZOQzBjb1BXT3ZPMDRuL0g4a01oUnAvOTNkNXNMajNHRApZM202OTYzMk8y
            dXhDbndTU0NLWGlnZFI3RytreExVLzQ0bUM1dkVmWHJzCi0tLSA3NmdObFg0OVFK
            cXRCWkdHbG5xYXZncldXV05oMzNkNFA5Zy9YdlRmT0ZzCvw06AM5+vQd9QwVWKuT
            X2ad9Ftn5wW02JMsPJYfoYFR85ufwuG/gziJdDM7nYOqboaMeaMDyLM1hR4W5BHh
            VL4=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBMTMwRFVj
            NVlMT3prMm9heVVWaElzZ0o3d1ZqMHlFYmFzZVlVWm9RcTJGVwpVZ2NLVHpmYWt0
            enBFK3EzOUljTm9Qa09ocVdiQjd4RHBFQjhTQktVSVFvCi0tLSBiRWdxOFRneC8v
            c2hseGcrTlFjOFBERzVxQ20wUWtVNEVNMDlOZnQxNVpJCu96VTvAKuKqqylJMVyc
            3r79da/ZHxI1NC7EQI7cTiByBZbh6MK7mVKYXL5vmGKWU2oLN4p2laRjCZVTOmP9
            FpI=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWnlGU0E1WVk5djI4bWNr
            eFRkWG9Sbkc0SHA5L1R1dW5WR2J2bGxOS0FvCk85VVpjb1pIYW92OENUbFdkY0Q3
            QjhZNUlSMUdTRHQ3d1BCc24yQkx3SjQKLS0tIFB5bWpyWHh6dFJvU2dEUGs4L3lQ
            My9lQWdjdjBSMlVTUjdac2wxM3BTQlEK3dMg4ib/LK3txnokm6j10K/7y1GWJQ8E
            XYYXPYII/1LBYtSywtvr9BnJ7rCz9JJNwR6sv8ZMSYsNe/nr8gw3XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T00:57:20Z"
    mac: ENC[AES256_GCM,data:jPJzuWEfThDPmXJzPEuhO0EJ1PG3N0BCPr51q//j3OULmdrIY1dxPcKxcvtUtMrzz8G77AxzLfRaTKAJiyRncbMf4KXazbh2tHEl7FFQzwoV0dDFPxPTmwC9X829AH+IsUKc/LCCoLiLFmZmmsJfV339MahaGLrqffEGH3XlV/Y=,iv:RNdV8VKYrKYxivaBQjbEKb5BJYC5iworVR+mCVz4Sx8=,tag:5Cj5mHLw1Yyp0Xb+GY1a8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
