apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helm-release.yaml
  - resources/oci-repo.yaml
  - resources/synapse-pg/postgres.yaml
  - resources/synapse-pg/db-secret.yaml
  - resources/mas-pg/postgres.yaml
  - resources/mas-pg/db-secret.yaml
  - resources/science-team-oicd.yaml
  - resources/turn-tls-ingress-route.yaml