apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-config
stringData:
    unpackerr.conf: ENC[AES256_GCM,data:aVN5cPBxEMmxpMWGjdiBE4YVoXA/GnQZa1Y5Or7acMDTzEpSkmGU/bo/3sc68h2zbz3TMatPeyZszwM2XjXXv8ADc8O2/NbqgCWotfANKWzomcb4Ld3aaWDuniAw9tVTzaoj9wV9BlNLINqHKNYEmuvwAtpKiiMPbqXrLMheT8ur66nMkMGsLZ+bKqRvTMsMbWinI2crqxZwEmdNk7n7mc24RW3OCoDx6ljOxgABm2xkJe98aIk0BRgA1AVtb070oZy1bmJslrEFAPv2twpk2cCTPEn9fh74JCCnMYVc2gL9YwacRB5QfZrunMBJ4gJDcG5blanrZcfL6kYTQR6Ct36NnJOk0vXQfCOKQusB0RX+BWhGwt160qZ9h2y8CSutdLncRpKqgs9REf9g083xjAg+VlJiGgpiLczpQLtTOYcfDzGQ+yV+fPswXNdcRh+Lk0+nENsdVC9SRK5z3Jtimr3rqJZiYYsDBmSUMY1qgd8z6dnRlPdo8adcZDZpDG8z18zD7qQblHTN4R8AkuwelCV5zm3/Z6IOtbSKnjhwdo8bWQW2Zd5rjbrqwi38BImmMVKSUOLRF2KgZxDSag7eEDPZ5yrm4SHjr/1ge/w9Vdc5KfJF7F0xvxqE1v4niNnFLM7Yuz0CRswCflexcbumq7mYx5L+j2yLzVvJU8VH9dDpTSOF5DMq3qNXaiD/IrNhEawaWjWdl5pi3fSM9PbspxP98YtczqOVv2mBFW0OEqjyNTieOwmp6Jo385WNODIf7bb8Cy22deVeYUUKUlRWkxCgB68RUtp2YsuOJY03gyNwkvJhv7UUqtHbcuwSIt5+7sAXpJJpO8eAWravcPvlWRnsUUdlE7QoehlBYqYKUDLkwAGsc9RhmjiTiPqfERB4WUtz4zobXSLTuEAP8BluU6to7d+hfQ8yYEsTLwt+QLr3MP31f4SSCNAGqxivPYEKnNA2FHbgf3U+8cu/p3WfBwDOUN2S9JuhIIsTgIYYtEPYjf825+27qkWlGAT2L8UKzLZW6OcSYFtS+oHsSXvUROdqaPKJ/ZO/22aD/5k3DxLPYUIWm7F8KSU2S2iPAz+dbjsS1r8zr5uniofJ8AJ2VYFjlvjgfllFG2rKRLSCgs3xIrEpmK30nS47KpuwKbvVEtkwlC6XcAzTUc3aEx9FFSixw+1yq5y6oNBdi/xmQz0CoZOQp1iNo94qQcQyTZq2VZUkQ82BQccEgh3LJPQqg52MvmyWQ8nbOQ==,iv:Q/r23ahCPbBjVmWySLWIpXXDkcODofaX1OUyc/7fvSE=,tag:OOKyuhPbjcqxmz/HSnHUaw==,type:str]
sops:
    age:
        - recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBclhQZUVj
            TGVBSklRd2Qvd1ZFaVVxRnEyUlRQTkp1NXJDRnhmYm16ai9iWgpMTURXdC9PSFMx
            Y0R5L0gxSGloeTg3Mm03QzVycTg5QVFBRjNoTTVPR0tjCi0tLSA4ekUyU3daVHR1
            cVN6eTY5RTYydFhTN3pGTWEyd0hPU0Vlbk4zalloVkJFCkAC51XY/muBDCHzQ6WS
            u0MwaX+T5HdgkUo0unVI4EDf3lzG4s8xlnI7NLUKgxaGMnArQzWBvgm/uZuOAXWE
            IPk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBejBjTGtt
            K3hVMmUybDVGM2FMYkQxelJUY1NDUmFkSTlBZ0piOGZtV2gveAp2M0lDTDRtc3Ji
            OGdYYTlNY00xZk9PdFkvTnRML1Fjd2l1MVVoRk5NY20wCi0tLSBhWDZGd0VCVlh4
            YlNKZU9VVSt4NnFMQXVsZDFOa0laNHh3L0tyOFdzUlF3CrXT2ONolyh7epsRLeMP
            YGoOTJ63ny7nu/Fvs5fjMmHf01GmHRHsaTTv6axBPS9Lxiawau21swi++PkaksRE
            40M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cW9rcXlSTHBpdXN6NGN1
            OHljaHpMU1cyS3VGcERMTzFYZnhNU0k0MHpVCmRNRGZSK05TMUh2d2l2aVhDRnpJ
            Rkh3ZXFxVUd5d29VYVF4Y3hLY1l0UFUKLS0tIE5aMUk1Z29kUXN3WlQwZm9YNm9H
            ajk1MC9YNVV2Ykt3cWVxc0lHVy9VZDAKA5anKje8Ir0DNwAWzX+Tw97scTCwn6uF
            X+9AVBxAo84DzMCWka/R9yr/grOZVh3eepdho/fVB1s9GC+qo7NbHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T02:22:21Z"
    mac: ENC[AES256_GCM,data:NYpEPRPFml4aEmnU/d56HVRi3OlDiUiraSAZsbHZzLgFzbJ1shWzJqSu9C/8JW3sT3eSUuS94dMf0xQGGft+FLmLKU0KQkKsKBK/ZqXdIeH/PQUqiO9aBNUjbaz3kce4ViVaTejKtfkz9Vlvk24cGHJkoOKcWYVbbP9xcWNfj/U=,iv:2t2hZeN+80NPgdz4nL+WADLQiFTJs2JEYStQRioZuS0=,tag:esduWuex33ANS3xqo1qndA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
