apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-config
stringData:
    unpackerr.conf: ENC[AES256_GCM,data:/WAaFGw1v6gCtjwbJRE2ToaLWWmFMSqBFkehHQCOfFjZoyKLw20xB/rQW+UOt/p1rWsD6vhG2oZizBrG+GILeUsXArQ1uHfJ+gGP3cRgKaYZ2nyj2l7DmvbC7Y4QXERWmdYsfygQS4p0cyXEedSkGlriNCqBU1YJNbrIaTrMS6pSf0cqEZSkOWOateecyARrmIX1vgrFadtzftEDMDN52YVIWVmFxzme/NW5sq8zSRFa9SDclklGYuByLgcQDPMM+kgKu5Z1sfm2eEXYX+GZOrDZuZgvb84Q4d+XlCJID3DdPQNWOX8urMqFdcV+DHXeOkypv1w5Iiz4wKjEdhscZxWv4lRXLQPMTXAsn6d1w0qWIkPBI20lvaOQZLU8V0k02z0fvrX2OJJW5AaSGGLqDTI3ccl8G99nN5H0crx/Dizyq+Hrc50WthCVQtYnNi+yJu19mFbs+2wGx8QoOgmvCfikJHD9hcPGrdrzFTBb4cQeE8WhcRuoYzsvCbRQ7iuK/z4eyR8YcEK/A1s525OqSfbhxFssRPKkJOQx9TLI1lU/ZLvVbVeFHek2ivbO/en62HCaMqDd+XNtu+TrGEyooP+ogdRsLVdwX/k/ERe2cGd3s/Cp+odOqTWhsAvzci1sOVMyk4Kxh15dKBEiSK5N49Ne7qLZwRL2BHnA3nBBTC1LRWICK0JdZ/yIGKu+HqO83nl980L8YgWEcS8rBuulqfPGoZegYxwIpo04KGl3UIAI5zYGxDNUojPO1N76udtgBPpfUjGBfVAyz4R3VVu2A0Ws8/cUlD21z3nBlEEAzlV3trizwH4eljF3QD100cqS80/KL6RlzJ/0Zvcrm9EsCCV9gst6n3b7e+C6nA7E1ItFaPsyo5mXhuS7tQQ8DynDe/GwW9htuJ+NllZaJ4Ch8i6Cmtiv/eLTCia3SLtFy9DrqXz5ElIFkjRDshhd14SpCY9RWaGGrJdlU2nt9maQETJr4FSd6idzH/xrLgUUw0veB3NNU7HM2eKNLZyTP4LirfrBzAAA4HRnVv53/vVAuPVP7phHnSAy34e3c7Jkpppa3ASvittSoRkXX4QEft6gP/RafYUktJ1KLKZ8A3K+IwZyXIc6f7xcdGbljyw9YvA0Tl2UxSSrxb+qlb8/mH9cmp/caHP8PTAS2G6kdTCDr+f6grXVtOhZ1ckZhi7ZrYQZ+rlFniuqSaMjY6BJsE/Xf5VqSQ/xtHonPqtaf1EelOnyv/mWLXsnWw==,iv:uh2wo2oRw0Hyb6uTKHuIjofDxHSVZHVXdM3ME4M6wg8=,tag:g9SPZS1HgHIxOSf5VoEwTg==,type:str]
sops:
    age:
        - recipient: age1yubikey1qdmjd6g9zxszvw332nlw8898pl9q8tnpjv8ljjvxpau650567j5a6nlpjz8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEcvTERKZyBBclhQZUVj
            TGVBSklRd2Qvd1ZFaVVxRnEyUlRQTkp1NXJDRnhmYm16ai9iWgpMTURXdC9PSFMx
            Y0R5L0gxSGloeTg3Mm03QzVycTg5QVFBRjNoTTVPR0tjCi0tLSA4ekUyU3daVHR1
            cVN6eTY5RTYydFhTN3pGTWEyd0hPU0Vlbk4zalloVkJFCkAC51XY/muBDCHzQ6WS
            u0MwaX+T5HdgkUo0unVI4EDf3lzG4s8xlnI7NLUKgxaGMnArQzWBvgm/uZuOAXWE
            IPk=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qwu0zwltgvjgv7tr0qcpjw6grreja8lqwpsxdprgwyap29mrkvx6j6795r0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1TL0VLZyBBejBjTGtt
            K3hVMmUybDVGM2FMYkQxelJUY1NDUmFkSTlBZ0piOGZtV2gveAp2M0lDTDRtc3Ji
            OGdYYTlNY00xZk9PdFkvTnRML1Fjd2l1MVVoRk5NY20wCi0tLSBhWDZGd0VCVlh4
            YlNKZU9VVSt4NnFMQXVsZDFOa0laNHh3L0tyOFdzUlF3CrXT2ONolyh7epsRLeMP
            YGoOTJ63ny7nu/Fvs5fjMmHf01GmHRHsaTTv6axBPS9Lxiawau21swi++PkaksRE
            40M=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tufq3ztwqlaawpe4sd8pzh7t70fvgq8wwz7q0mka2rvrgvtngsgqhxay7r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cW9rcXlSTHBpdXN6NGN1
            OHljaHpMU1cyS3VGcERMTzFYZnhNU0k0MHpVCmRNRGZSK05TMUh2d2l2aVhDRnpJ
            Rkh3ZXFxVUd5d29VYVF4Y3hLY1l0UFUKLS0tIE5aMUk1Z29kUXN3WlQwZm9YNm9H
            ajk1MC9YNVV2Ykt3cWVxc0lHVy9VZDAKA5anKje8Ir0DNwAWzX+Tw97scTCwn6uF
            X+9AVBxAo84DzMCWka/R9yr/grOZVh3eepdho/fVB1s9GC+qo7NbHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:15:15Z"
    mac: ENC[AES256_GCM,data:4mp9PhVXzx+ZqaYJc7UwsPgLNgU0bXipdlji5HbRACg6XKS/glFxOlQzq6EeuwYvHpR2siIHxsy/zAAeo4T1IueXZx6taW4mCfT6D7l2vnlY4U1X7TMB3mendIRhWA8/O7CPSFvGRCX1R2pmbm4jHjQkOjJ5TtRJ+RyvowdKcEc=,iv:SFRsAxLQdt1aQ8IG+zp9VDG2dJHGAZRWHrk/r0yNBMQ=,tag:/PXTm7Ax6Iw8ZXGs4VDNlg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
