apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - calibre/ks.yaml
  - calibre-web/ks.yaml
  - flood/ks.yaml
  - immich/ks.yaml
  - jellyfin/ks.yaml
  - overseerr/ks.yaml
  - paperless-ngx/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - readarr/ks.yaml
  - sonarr/ks.yaml
  - sonarr-anime/ks.yaml
  - syncthing/ks.yaml
  - tdarr/ks.yaml
  - unpackerr/ks.yaml
  - watchstate/ks.yaml
  - gonic/ks.yaml

