apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - immich/ks.yaml
  - jellyfin/ks.yaml
  - paperless-ngx/ks.yaml
  - plex/ks.yaml
  - syncthing/ks.yaml
  - watchstate/ks.yaml
  - gonic/ks.yaml
  - booklore/ks.yaml
