apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cilium-gateways/ks.yaml
  - externaldns-cloudflare/ks.yaml
  - externaldns-local/ks.yaml
  - externaldns-repo/ks.yaml
