apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helm-release.yaml
  - resources/oci-repo.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.10.0/manifest.yaml