apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - esphome/ks.yaml
  - frigate/ks.yaml
  - hass/ks.yaml
  - mqtt/ks.yaml
  - nodered/ks.yaml
  - xcel-itron2mqtt/ks.yaml
  - music-assistant/ks.yaml
