apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: svcs
resources:
  - cloudflare-ddns/ks.yaml
  - hydroxide/ks.yaml
  - jmusicbot/ks.yaml
  - actual/ks.yaml
  - namespace.yaml
