apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/helm-release.yaml
  - resources/oci-repo.yaml
  - resources/cloudflare-api-token-secret.yaml
  - resources/letsencrypt-cloudflare-issuer.yaml