apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flood/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - seerr/ks.yaml
  - sonarr/ks.yaml
  - sonarr-anime/ks.yaml
  - unpackerr/ks.yaml